# Mountain Theme (stolen from Catppuccin github repo)

[colors]
foreground = "#f0f0f0"
background = "#0f0f0f"
cursor_bg = "#f0f0f0"
cursor_fg = "#f0f0f0"
cursor_border = "#262626"
split = "#4c4c4c"

ansi = [ "#8f8aac", "#ac8a8c", "#8aac8b", "#aca98a", "#9ec3c4", "#ac8aac","#8aabac", "#f0f0f0" ]
brights = [ "#a39ec4", "#ac8a8c", "#8aac8b", "#aca98a", "#9ec3c4", "#ac8aac", "#9aabac", "#f0f0f0" ]
